version: "3.8"
services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: django-docker
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: vite-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped

volumes:
  frontend_node_modules:
