# Generated by Django 5.2.1 on 2025-05-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='image',
        ),
    ]
