# Generated by Django 5.2.1 on 2025-05-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_remove_appuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
    ]
